// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Greenovative.Accounting.Infrastructure.Models;

public partial class AccountType
{
    public byte Id { get; set; }

    public string AccountType1 { get; set; }

    public string Description { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<AccountCategory> AccountCategories { get; set; } = new List<AccountCategory>();

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}