// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Greenovative.Accounting.Infrastructure.Models;

public partial class Account
{
    public string Id { get; set; }

    public string AccountNo { get; set; }

    public string ClientId { get; set; }

    public string AccountName { get; set; }

    public byte? AccountTypeId { get; set; }

    public byte? AccountCategoryId { get; set; }

    public string Description { get; set; }

    public decimal? OpeningBalance { get; set; }

    public string DebitCredit { get; set; }

    public byte? LedgerAccount { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual AccountCategory AccountCategory { get; set; }

    public virtual AccountType AccountType { get; set; }

    public virtual ICollection<Voucher> VoucherCreditAccounts { get; set; } = new List<Voucher>();

    public virtual ICollection<Voucher> VoucherDebitAccounts { get; set; } = new List<Voucher>();
}