// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Greenovative.Accounting.Infrastructure.Models;

public partial class Voucher
{
    public string Id { get; set; }

    public string VoucherNo { get; set; }

    public string ClientId { get; set; }

    public string CreditDebit { get; set; }

    public decimal? CreditAmount { get; set; }

    public decimal? DebitAmount { get; set; }

    public byte? VoucherTypeId { get; set; }

    public string DebitAccountId { get; set; }

    public string CreditAccountId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual Account CreditAccount { get; set; }

    public virtual Account DebitAccount { get; set; }

    public virtual VoucherType VoucherType { get; set; }
}