// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Greenovative.Clients.Infrastructure.Models;

public partial class BusinessCategory
{
    public byte Id { get; set; }

    public string BusinessCategoryName { get; set; }

    public string Description { get; set; }
}