// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Greenovative.Clients.Infrastructure.Models;

public partial class Client
{
    public Guid Id { get; set; }

    public string ClientFName { get; set; }

    public string ClientMName { get; set; }

    public string ClientLName { get; set; }

    public string AddressId { get; set; }

    public string ContactId { get; set; }

    public string IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTimeOffset? ModifiedOn { get; set; }

    public virtual Address Address { get; set; }

    public virtual Contact Contact { get; set; }

    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();
}