// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Greenovative.Clients.Infrastructure.Models;

public partial class Contact
{
    public string Id { get; set; }

    public string HomePhone { get; set; }

    public string OfficePhone { get; set; }

    public string CellPhone { get; set; }

    public string Email1 { get; set; }

    public string Email2 { get; set; }

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();
}