// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Greenovative.Identity.Infrastructure.ClientModels;

namespace Greenovative.Identity.Infrastructure.Models;

public partial class AspNetUserRole
{
    public Guid UserId { get; set; }

    public Guid RoleId { get; set; }

    public Guid ClientId { get; set; }

    public int? StoreId { get; set; }

    public virtual Client Client { get; set; }

    public virtual AspNetRole Role { get; set; }

    public virtual Store Store { get; set; }

    public virtual AspNetUser User { get; set; }
}