// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Greenovative.Identity.Infrastructure.ClientModels;
using Microsoft.AspNetCore.Identity;

namespace Greenovative.Identity.Infrastructure.Models;

public partial class AspNetUserRole : IdentityUserRole<Guid>

{
    public Guid UserId { get; set; }

    public Guid RoleId { get; set; }

    public Guid ClientId { get; set; }

    public int? StoreId { get; set; }

    public virtual Client Client { get; set; }

    public virtual Role Role { get; set; }

    public virtual Store Store { get; set; }

    public virtual User User { get; set; }
}