// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Greenovative.Identity.Infrastructure.ClientModels;

public partial class BusinessCategory : BaseModel
{
    public byte Id { get; set; }

    public string BusinessCategoryName { get; set; }

    public string Description { get; set; }
}