// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Greenovative.Identity.Infrastructure.Models;

namespace Greenovative.Identity.Infrastructure.ClientModels;

public partial class Store : BaseModel
{
    public int Id { get; set; }

    public Guid ClientId { get; set; }

    public string StoreNumber { get; set; }

    public string StoreName { get; set; }

    public string RegisteredName { get; set; }

    public string TINNo { get; set; }

    public byte? BusinessTypeId { get; set; }

    public byte? BusinessCategoryId { get; set; }

    public string ContactId { get; set; }

    public string AddressId { get; set; }

    public bool? IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTimeOffset? ModifiedOn { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; } = new List<AspNetUserRole>();

    public virtual Client Client { get; set; }

    public virtual Contact Contact { get; set; }
}