// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Greenovative.Identity.Infrastructure.ClientModels;

public partial class UserClientRole : BaseModel
{
    public int Id { get; set; }

    public Guid? UserId { get; set; }

    public Guid? ClientId { get; set; }

    public int? StoreId { get; set; }

    public int? RoleId { get; set; }

    public bool? IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTimeOffset? ModifiedOn { get; set; }
}